pipeline {
    agent any
    environment{
        DATABASE_URI = credentials("DATABASE_URI")
        DB_PASSWORD = credentials("DB_PASSWORD")
        AUTHOR = credentials("AUTHOR")
        app_version = '2.0'
        rollback = 'false'
        replicas = 3
    }
    stages {
        stage('Testing') {
            steps{
                script{
                    if (env.rollback == 'false'){
                        sh 'bash jenkins/test.sh'
                    }
                }
            }
        }
        stage('Build & Push') {
            steps {
                script {
                    if (env.rollback == 'false'){
                        sh 'bash jenkins/build_images.sh'
                    }
                }
            }
        }
        stage('Config Management (ansible)') {
            steps {
                sh 'bash jenkins/config.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh 'bash jenkins/deploy.sh'
            }
        }
    }
}
